version: "3"

services:
  backend:
    build:
      context: .
      target: Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app/Backend
      - ./LIVE_YOUR_STYLE.sqlite3:/app/LIVE_YOUR_STYLE.sqlite3
    command: ["python3", "manage.py", "runserver", "--settings=core.settings.dev"]
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      target: Frontend
    ports:
      - "4200:4200"
    volumes:
      - ./Frontend:/app/Frontend

