# Generated by Django 4.2.3 on 2023-07-21 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Marca', '0001_initial'),
        ('Unidad_medida', '0001_initial'),
        ('Color', '0001_initial'),
        ('Categoria_producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('precio', models.FloatField()),
                ('costo', models.FloatField()),
                ('original', models.BooleanField()),
                ('color', models.ManyToManyField(blank=True, to='Color.color')),
                ('id_cat_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categoria_producto.cat_prod')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marca.marca')),
                ('id_u_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Unidad_medida.unidad_medida')),
            ],
        ),
    ]
