# Generated by Django 4.2.3 on 2023-07-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_alta', models.DateField()),
                ('dni', models.IntegerField()),
                ('cuit', models.CharField(max_length=12)),
            ],
        ),
    ]
